(()=>{
const API='http://localhost:3000/api';
const $=s=>document.querySelector(s);
let categorias=[], categoriaActual=null, productos=[], meta={}, pagina=1;
let carrito=(()=>{try{const lista=JSON.parse(localStorage.getItem('tiendapro_carrito_publico')||'[]');return Array.isArray(lista)?lista:[]}catch{return[]}})();
const esc=t=>String(t??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
function imageUrl(v){if(!v)return'';let s=String(v).trim();if(!s)return'';if(/^https?:\/\//i.test(s)||s.startsWith('data:')||s.startsWith('blob:'))return s;if(s.startsWith('/'))return `http://localhost:3000${s}`;return `http://localhost:3000/${s.replace(/^\.\//,'')}`}
function imagenProducto(p){return imageUrl(p.imagen||p.imagen_principal||p.foto||'')}
function precioFinal(p){const base=Number(p?.coincidencia_variante?.precio ?? p?.precio ?? 0);const d=Number(p?.descuento||0);return Math.max(0,base-(base*d/100))}
function usuarioActual(){try{return JSON.parse(localStorage.getItem('usuario')||'null')}catch{return null}}
function sesionCliente(){const u=usuarioActual();return Boolean(localStorage.getItem('token')&&localStorage.getItem('portalSesion')==='tienda'&&String(u?.rol||'').toLowerCase()==='cliente')}
function claveFavoritos(){const u=usuarioActual();return `tiendapro_favoritos_cliente_${u?.id||u?.email||'invitado'}`}
function leerFavoritos(){try{const lista=JSON.parse(localStorage.getItem(claveFavoritos())||'[]');return Array.isArray(lista)?lista:[]}catch{return[]}}
function esFavorito(id){return leerFavoritos().some(p=>Number(p.id)===Number(id))}
function cantidadCarrito(id){return Number(carrito.find(p=>Number(p.id)===Number(id))?.cantidad||0)}
function aviso(texto){let el=document.getElementById('avisoCategoria');if(!el){el=document.createElement('div');el.id='avisoCategoria';el.className='store-toast';el.setAttribute('role','status');document.body.appendChild(el)}el.textContent=texto;el.classList.add('show');clearTimeout(aviso.timer);aviso.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function guardarCarrito(){localStorage.setItem('tiendapro_carrito_publico',JSON.stringify(carrito));const total=carrito.reduce((n,p)=>n+Number(p.cantidad||0),0);['#sharedCartCount','#sharedCartCountCliente'].forEach(s=>{const el=$(s);if(el)el.textContent=total});document.querySelectorAll('[data-card-cart-id]').forEach(btn=>{const n=cantidadCarrito(btn.dataset.cardCartId),badge=btn.querySelector('.product-cart-quantity');btn.classList.toggle('has-items',n>0);if(badge){badge.textContent=n;badge.hidden=n===0}})}
function agregarDesdeTarjeta(e,id){e.preventDefault();e.stopPropagation();const p=productos.find(x=>Number(x.id)===Number(id));if(!p)return;const stock=Number(p.coincidencia_variante?.stock??p.stock_fisico_disponible??p.stock??0);if(stock<=0&&!p.permite_bajo_pedido){aviso('Este producto está agotado.');return}const item=carrito.find(x=>Number(x.id)===Number(id));if(item)item.cantidad=Number(item.cantidad||0)+1;else carrito.push({id:p.id,nombre:p.nombre,precio:precioFinal(p),imagen:imagenProducto(p),cantidad:1});guardarCarrito();aviso('Producto agregado al carrito.')}
function alternarFavorito(e,id){e.preventDefault();e.stopPropagation();if(!sesionCliente()){aviso('Inicia sesión para guardar favoritos.');setTimeout(()=>location.href='login-cliente.html',700);return}const p=productos.find(x=>Number(x.id)===Number(id));if(!p)return;let lista=leerFavoritos();const existe=lista.some(x=>Number(x.id)===Number(id));lista=existe?lista.filter(x=>Number(x.id)!==Number(id)):[{id:p.id,nombre:p.nombre,precio:precioFinal(p),imagen:imagenProducto(p),tienda:p.tienda||p.marca||'TiendaPro',estado_visual:p.estado_visual||'',guardado_en:Date.now()},...lista];localStorage.setItem(claveFavoritos(),JSON.stringify(lista));const btn=e.currentTarget;btn.classList.toggle('active',!existe);btn.setAttribute('aria-pressed',String(!existe));btn.title=existe?'Agregar a favoritos':'Quitar de favoritos';aviso(existe?'Producto eliminado de favoritos.':'Producto guardado en favoritos.')}
function reviews(p={}){const promedio=Math.max(0,Math.min(5,Number(p.calificacion_promedio??p.promedio_resenas??p.rating??0)||0));const total=Math.max(0,Number(p.total_resenas??p.cantidad_resenas??p.reviews_count??0)||0);return{promedio,total}}
function stars(v){const n=Math.max(0,Math.min(5,Math.round(Number(v)||0)));return '★'.repeat(n)+'☆'.repeat(5-n)}
function resolverCategoria(){const q=new URLSearchParams(location.search);const id=Number(q.get('categoria_id')||0);if(id)return categorias.find(c=>Number(c.id)===id)||null;const name=String(q.get('category_name')||'').trim().toLowerCase();return categorias.find(c=>String(c.name||c.nombre||'').trim().toLowerCase()===name)||null}
function rutaCategoria(cat){const byId=new Map(categorias.map(c=>[Number(c.id),c]));const arr=[];let cur=cat, guard=0;while(cur&&guard++<10){arr.unshift(cur);const pid=cur.parent_id===null||cur.parent_id===undefined||cur.parent_id===''?null:Number(cur.parent_id);cur=pid?byId.get(pid):null}return arr}
async function cargarCategorias(){const r=await fetch(`${API}/productos/publicos/categorias`);if(!r.ok)throw new Error('categorias');categorias=await r.json();categoriaActual=resolverCategoria();if(!categoriaActual){const q=new URLSearchParams(location.search);const requested=String(q.get('category_name')||'').trim();if(requested)categoriaActual={id:null,name:requested,nombre:requested,parent_id:null,_virtual:true};}if(!categoriaActual)throw new Error('categoria-no-encontrada');const ruta=categoriaActual._virtual?[categoriaActual]:rutaCategoria(categoriaActual);$('#categoryTitle').textContent=categoriaActual.name;$('#categoryProductsTitle').textContent=`Productos de ${categoriaActual.name}`;$('#categoryBreadcrumbText').textContent=ruta.map(x=>x.name).join(' › ');document.title=`${categoriaActual.name} | TiendaPro`;}
async function cargarMarcas(){
  const sel=$('#marcaPublica');if(!sel)return;
  const actual=sel.value;
  sel.innerHTML='<option value="">Todas las marcas</option>';
  const p=new URLSearchParams();
  if(categoriaActual?.id)p.set('categoria_id',categoriaActual.id);
  else if(categoriaActual?.name)p.set('categoria',categoriaActual.name);
  try{
    const url=`${API}/productos/publicos/marcas${p.toString()?`?${p.toString()}`:''}`;
    const r=await fetch(url);
    const ms=await r.json();
    (ms||[]).forEach(m=>{const o=document.createElement('option');o.value=m;o.textContent=m;sel.appendChild(o)});
    sel.value=(ms||[]).includes(actual)?actual:'';
  }catch{}
}
function params(){const p=new URLSearchParams();if(categoriaActual.id)p.set('categoria_id',categoriaActual.id);else p.set('categoria',categoriaActual.name);const marca=$('#marcaPublica').value,min=$('#precioMin').value,max=$('#precioMax').value;if(marca)p.set('marca',marca);if(min)p.set('precio_min',min);if(max)p.set('precio_max',max);if($('#soloOfertas').checked)p.set('ofertas','1');p.set('orden',$('#ordenPublico').value);p.set('page',pagina);p.set('limit','20');return p}
async function cargarProductos(reset=false){if(reset)pagina=1;const estado=$('#estadoPublico');estado.hidden=true;try{const r=await fetch(`${API}/productos/publicos?${params()}`);if(!r.ok)throw new Error();meta=await r.json();productos=meta.productos||[];render();paginacion();resumen()}catch{productos=[];$('#productosPublicos').innerHTML='';estado.hidden=false;estado.textContent='No se pudo cargar esta categoría. Verifica que el servidor esté ejecutándose.';$('#resumenProductos').textContent='Catálogo no disponible'}}
function render(){
  const grid=$('#productosPublicos'),estado=$('#estadoPublico');
  if(!productos.length){grid.innerHTML='';estado.hidden=false;estado.textContent='Todavía no hay productos publicados en esta categoría.';return}
  estado.hidden=true;
  grid.innerHTML=productos.map(p=>{
    const fin=precioFinal(p),d=Number(p.descuento||0),stock=Number(p.coincidencia_variante?.stock??p.stock_fisico_disponible??p.stock??0),rv=reviews(p),base=Number(p.coincidencia_variante?.precio??p.precio??0),entrega=String(p.tiempo_entrega||'Según disponibilidad').trim(),favorito=esFavorito(p.id),cantidad=cantidadCarrito(p.id),agotado=stock<=0&&!p.permite_bajo_pedido;
    return `<article class="product-card product-card-clickable" role="link" tabindex="0" data-product-id="${p.id}"><div class="product-image">${imagenProducto(p)?`<img src="${imagenProducto(p)}" alt="${esc(p.nombre)}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="placeholder" style="display:none">📦</span>`:'<span class="placeholder">📦</span>'}${d>0?`<span class="product-discount-ribbon">-${d}%</span>`:''}<div class="product-actions"><button class="product-action-favorite ${favorito?'active':''}" type="button" title="${favorito?'Quitar de favoritos':'Agregar a favoritos'}" aria-label="${favorito?'Quitar de favoritos':'Agregar a favoritos'}" aria-pressed="${favorito}" data-card-favorite-id="${p.id}">❤</button></div></div><div class="product-body"><div class="product-brand">${esc(p.tienda||p.marca||'TiendaPro')}</div><h3 class="product-title">${esc(p.nombre)}</h3><div class="product-delivery-time"><span aria-hidden="true">🚚</span><span>Entrega: ${esc(entrega)}</span></div><div class="product-category">${esc(p.categoria||categoriaActual.name)}</div><div class="product-rating"><span class="product-rating-stars">${stars(rv.promedio)}</span><span class="product-rating-text">${rv.total?`${rv.promedio.toFixed(1)} (${rv.total})`:'Sin reseñas'}</span></div><div class="badges"><span class="badge ${stock>0?'ok':'warn'}">${stock>0?'Disponible':'Agotado'}</span>${stock>0?`<span class="badge">Stock ${stock}</span>`:''}</div><div class="price-row"><span class="price">${money(fin)}</span>${d>0?`<span class="old-price">${money(base)}</span>`:''}<button class="product-action-cart ${cantidad>0?'has-items':''}" type="button" data-card-cart-id="${p.id}" title="${agotado?'Producto agotado':'Agregar al carrito'}" ${agotado?'disabled':''}>🛒<span class="product-cart-quantity" ${cantidad>0?'':'hidden'}>${cantidad}</span></button></div></div></article>`
  }).join('');
  grid.querySelectorAll('[data-card-cart-id]').forEach(btn=>btn.addEventListener('click',e=>agregarDesdeTarjeta(e,btn.dataset.cardCartId)));
  grid.querySelectorAll('[data-card-favorite-id]').forEach(btn=>btn.addEventListener('click',e=>alternarFavorito(e,btn.dataset.cardFavoriteId)));
  grid.querySelectorAll('[data-product-id]').forEach(c=>{const go=()=>location.href=`producto.html?id=${c.dataset.productId}`;c.addEventListener('click',go);c.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();go()}})});
}
function resumen(){const n=Number(meta.total||productos.length);$('#resumenProductos').textContent=`${n} producto${n===1?'':'s'} en ${categoriaActual.name}`;const parts=[categoriaActual.name];if($('#marcaPublica').value)parts.push($('#marcaPublica').value);if($('#soloOfertas').checked)parts.push('Ofertas');$('#filtrosActivos').textContent=parts.join(' · ')}
function paginacion(){const box=$('#paginacionPublica'),total=Number(meta.totalPaginas||1);if(total<=1){box.innerHTML='';return}let h=`<button ${pagina<=1?'disabled':''} data-page="${pagina-1}">‹</button>`;const a=Math.max(1,pagina-2),b=Math.min(total,a+4);for(let i=a;i<=b;i++)h+=`<button class="${i===pagina?'active':''}" data-page="${i}">${i}</button>`;h+=`<button ${pagina>=total?'disabled':''} data-page="${pagina+1}">›</button>`;box.innerHTML=h;box.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>{const x=Number(btn.dataset.page);if(x>=1&&x<=total){pagina=x;cargarProductos();scrollTo({top:document.querySelector('.category-intro').offsetTop-120,behavior:'smooth'})}})}
$('#ordenPublico').addEventListener('change',()=>cargarProductos(true));$('#aplicarFiltros').addEventListener('click',()=>cargarProductos(true));$('#limpiarFiltros').addEventListener('click',()=>{$('#marcaPublica').value='';$('#precioMin').value='';$('#precioMax').value='';$('#soloOfertas').checked=false;cargarProductos(true)});$('#btnFiltros').addEventListener('click',()=>$('#panelFiltros').classList.toggle('open'));
cargarCategorias().then(()=>cargarMarcas()).then(()=>cargarProductos(true)).catch(()=>{const e=$('#estadoPublico');e.hidden=false;e.textContent='No encontramos la categoría seleccionada.';$('#categoryTitle').textContent='Categoría no encontrada';$('#resumenProductos').textContent='';});
})();
