const API='http://localhost:3000/api';
const token=localStorage.getItem('token');
const usuario=(()=>{try{return JSON.parse(localStorage.getItem('usuario')||'null')}catch{return null}})();
const $=s=>document.querySelector(s);
const money=v=>`$${Number(v||0).toFixed(2)}`;
const esc=t=>String(t??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const fecha=v=>v?new Date(v).toLocaleString('es-SV',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
function sesionCliente(){return Boolean(token&&localStorage.getItem('portalSesion')==='tienda'&&String(usuario?.rol||'').toLowerCase()==='cliente')}
function salir(){localStorage.removeItem('token');localStorage.removeItem('usuario');localStorage.removeItem('portalSesion');location.href='login-cliente.html'}
if(!sesionCliente()) location.href='login-cliente.html';
$('#cerrarSesion')?.addEventListener('click',salir);
function abrirModal(){const m=$('#modalPedidoCliente');m.classList.add('open');m.setAttribute('aria-hidden','false')}
function cerrarModal(){const m=$('#modalPedidoCliente');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',cerrarModal));
$('#modalPedidoCliente').addEventListener('click',e=>{if(e.target.id==='modalPedidoCliente')cerrarModal()});
async function api(path,opts={}){const r=await fetch(`${API}${path}`,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${token}`}});if(r.status===401||r.status===403){salir();throw new Error('Sesión no válida')}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.mensaje||'No se pudo completar la solicitud');return data}
async function cargarPerfil(){try{const d=await api('/auth/mi-cuenta');const u=d.usuario;$('#nombreCliente').textContent=u.nombre||'Cliente';$('#correoCliente').textContent=u.email||'';$('#avatarCliente').textContent=(u.nombre||'C').trim().charAt(0).toUpperCase()}catch(e){mostrarError(e.message)}}
async function cargarPedidos(){const list=$('#listaPedidos');list.innerHTML='<div class="empty-state">Cargando tus pedidos...</div>';try{const d=await api('/pedidos/mis-pedidos');const pedidos=d.pedidos||[];if(!pedidos.length){list.innerHTML='<div class="empty-state">Todavía no has realizado pedidos. <a href="tienda_publica.html" style="color:#62ddf6">Explorar productos</a></div>';return}list.innerHTML=pedidos.map(p=>`<article class="order-card"><div><div class="order-code">${esc(p.codigo_pedido||('#'+p.id))}</div><div class="order-date">${fecha(p.fecha_pedido)}</div></div><div><span class="status ${esc(String(p.estado||'').toLowerCase())}">${esc(p.estado||'Pendiente')}</span><div class="order-meta">${esc(p.metodo_pago||'Sin método')}</div></div><div><div class="order-total">${money(p.total)}</div><div class="order-meta">Total</div></div><div><div class="order-code">${esc(p.numero_factura||'Pendiente')}</div><div class="order-meta">Factura</div></div><button class="order-open" onclick="verPedido(${Number(p.id)})">Ver detalle</button></article>`).join('')}catch(e){list.innerHTML='<div class="empty-state">No se pudieron cargar tus pedidos.</div>';mostrarError(e.message)}}
window.verPedido=async id=>{try{const d=await api(`/pedidos/mis-pedidos/${id}/detalles`);const p=d.pedido,items=d.detalles||[];$('#detallePedidoCliente').innerHTML=`<span class="eyebrow">Pedido</span><h2 class="detail-title">${esc(p.codigo_pedido||('#'+p.id))}</h2><p class="detail-sub">Realizado ${fecha(p.fecha_pedido)}</p><div class="detail-summary-grid"><div class="detail-box"><span>Estado</span><strong>${esc(p.estado||'Pendiente')}</strong></div><div class="detail-box"><span>Total</span><strong>${money(p.total)}</strong></div><div class="detail-box"><span>Método de pago</span><strong>${esc(p.metodo_pago||'—')}</strong></div></div><div class="detail-box"><span>Dirección de entrega</span><strong>${esc(p.direccion_envio||'—')}</strong></div><table class="detail-products"><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.nombre_producto)}</td><td>${Number(i.cantidad||0)}</td><td>${money(i.precio_unitario)}</td><td>${money(i.subtotal)}</td></tr>`).join('')}</tbody></table>${p.factura_id?`<div class="invoice-actions"><div class="invoice-name">${esc(p.numero_factura||'Factura disponible')}</div><button class="btn primary" onclick="abrirFactura(${Number(p.factura_id)})">Ver factura PDF</button></div>`:'<div class="invoice-actions"><div class="invoice-name">Factura pendiente de generación</div></div>'}`;abrirModal()}catch(e){mostrarError(e.message)}};
window.abrirFactura=async id=>{try{const r=await fetch(`${API}/facturas/mias/${id}/pdf`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===401||r.status===403){salir();return}if(!r.ok)throw new Error('No se pudo abrir la factura');const blob=await r.blob();const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){mostrarError(e.message)}};
function mostrarError(texto){const m=$('#mensajeCuenta');m.textContent=texto;m.hidden=false;setTimeout(()=>m.hidden=true,4500)}
function mostrarConfirmacion(texto){const m=$('#mensajeCuenta');m.textContent=texto;m.classList.add('success');m.hidden=false;setTimeout(()=>{m.hidden=true;m.classList.remove('success')},3000)}
function claveFavoritos(){return `tiendapro_favoritos_cliente_${usuario?.id||usuario?.email||'invitado'}`}
function leerFavoritos(){try{const lista=JSON.parse(localStorage.getItem(claveFavoritos())||'[]');return Array.isArray(lista)?lista:[]}catch{return []}}
function leerCarrito(){try{const lista=JSON.parse(localStorage.getItem('tiendapro_carrito_publico')||'[]');return Array.isArray(lista)?lista:[]}catch{return []}}
function renderFavoritos(){
  const list=$('#listaFavoritos'),favoritos=leerFavoritos(),total=$('#totalFavoritos');
  if(total)total.textContent=`${favoritos.length} producto${favoritos.length===1?'':'s'}`;
  if(!favoritos.length){list.innerHTML='<div class="empty-state">Todavía no guardaste productos. <a href="tienda_publica.html#catalogo">Explorar productos</a></div>';return;}
  list.innerHTML=favoritos.map(p=>`<article class="favorite-product"><a class="favorite-product-link" href="producto.html?id=${encodeURIComponent(p.id)}"><div class="favorite-product-image">${p.imagen?`<img src="${esc(p.imagen)}" alt="${esc(p.nombre)}" onerror="this.style.display='none';this.nextElementSibling.hidden=false"><span class="favorite-product-placeholder" hidden>📦</span>`:'<span class="favorite-product-placeholder">📦</span>'}</div><div class="favorite-product-body"><span class="favorite-product-store">${esc(p.tienda||'TiendaPro')}</span><h3>${esc(p.nombre)}</h3><strong class="favorite-product-price">${money(p.precio)}</strong></div></a><div class="favorite-product-actions"><button type="button" title="Agregar al carrito" aria-label="Agregar ${esc(p.nombre)} al carrito" onclick="agregarFavoritoAlCarrito(${Number(p.id)})">🛒</button><button class="remove-favorite" type="button" title="Quitar de favoritos" aria-label="Quitar ${esc(p.nombre)} de favoritos" onclick="quitarFavorito(${Number(p.id)})">♥</button></div></article>`).join('');
}
window.quitarFavorito=id=>{localStorage.setItem(claveFavoritos(),JSON.stringify(leerFavoritos().filter(p=>Number(p.id)!==Number(id))));renderFavoritos()};
window.agregarFavoritoAlCarrito=id=>{const p=leerFavoritos().find(x=>Number(x.id)===Number(id));if(!p)return;const carrito=leerCarrito(),item=carrito.find(x=>Number(x.id)===Number(id));if(item)item.cantidad=Number(item.cantidad||0)+1;else carrito.push({id:p.id,nombre:p.nombre,precio:Number(p.precio||0),imagen:p.imagen||'',cantidad:1});localStorage.setItem('tiendapro_carrito_publico',JSON.stringify(carrito));window.dispatchEvent(new Event('storage'));mostrarConfirmacion('Producto agregado al carrito.')};
$('#recargarPedidos').addEventListener('click',cargarPedidos);
cargarPerfil();renderFavoritos();cargarPedidos();
