(()=>{
const API='http://localhost:3000/api',$=s=>document.querySelector(s);
let productos=[],meta={},pagina=1,timer=null;
let carrito=(()=>{try{const lista=JSON.parse(localStorage.getItem('tiendapro_carrito_publico')||'[]');return Array.isArray(lista)?lista:[]}catch{return[]}})();
const esc=t=>String(t??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
function imageUrl(v){if(!v)return'';let s=String(v).trim();if(/^https?:\/\//i.test(s)||s.startsWith('data:')||s.startsWith('blob:'))return s;if(s.startsWith('/'))return `http://localhost:3000${s}`;return `http://localhost:3000/${s.replace(/^\.\//,'')}`}
function imagenProducto(p){return imageUrl(p.imagen||p.imagen_principal||p.foto||'')}
function precioFinal(p){const b=Number(p?.coincidencia_variante?.precio??p.precio??0),d=Number(p.descuento||0);return Math.max(0,b-b*d/100)}
function stars(v){const n=Math.max(0,Math.min(5,Math.round(Number(v)||0)));return '★'.repeat(n)+'☆'.repeat(5-n)}
function usuarioActual(){try{return JSON.parse(localStorage.getItem('usuario')||'null')}catch{return null}}
function sesionCliente(){const u=usuarioActual();return Boolean(localStorage.getItem('token')&&localStorage.getItem('portalSesion')==='tienda'&&String(u?.rol||'').toLowerCase()==='cliente')}
function claveFavoritos(){const u=usuarioActual();return `tiendapro_favoritos_cliente_${u?.id||u?.email||'invitado'}`}
function leerFavoritos(){try{const lista=JSON.parse(localStorage.getItem(claveFavoritos())||'[]');return Array.isArray(lista)?lista:[]}catch{return[]}}
function esFavorito(id){return leerFavoritos().some(p=>Number(p.id)===Number(id))}
function cantidadCarrito(id){return Number(carrito.find(p=>Number(p.id)===Number(id))?.cantidad||0)}
function aviso(texto){let el=document.getElementById('avisoOfertas');if(!el){el=document.createElement('div');el.id='avisoOfertas';el.className='store-toast';el.setAttribute('role','status');document.body.appendChild(el)}el.textContent=texto;el.classList.add('show');clearTimeout(aviso.timer);aviso.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function guardarCarrito(){localStorage.setItem('tiendapro_carrito_publico',JSON.stringify(carrito));const total=carrito.reduce((n,p)=>n+Number(p.cantidad||0),0);['#sharedCartCount','#sharedCartCountCliente'].forEach(s=>{const el=$(s);if(el)el.textContent=total});document.querySelectorAll('[data-card-cart-id]').forEach(btn=>{const n=cantidadCarrito(btn.dataset.cardCartId),badge=btn.querySelector('.product-cart-quantity');btn.classList.toggle('has-items',n>0);if(badge){badge.textContent=n;badge.hidden=n===0}})}
function agregarDesdeTarjeta(e,id){e.preventDefault();e.stopPropagation();const p=productos.find(x=>Number(x.id)===Number(id));if(!p)return;const stock=Number(p.coincidencia_variante?.stock??p.stock_fisico_disponible??p.stock??0);if(stock<=0&&!p.permite_bajo_pedido){aviso('Este producto está agotado.');return}const item=carrito.find(x=>Number(x.id)===Number(id));if(item)item.cantidad=Number(item.cantidad||0)+1;else carrito.push({id:p.id,nombre:p.nombre,precio:precioFinal(p),imagen:imagenProducto(p),cantidad:1});guardarCarrito();aviso('Producto agregado al carrito.')}
function alternarFavorito(e,id){e.preventDefault();e.stopPropagation();if(!sesionCliente()){aviso('Inicia sesión para guardar favoritos.');setTimeout(()=>location.href='login-cliente.html',700);return}const p=productos.find(x=>Number(x.id)===Number(id));if(!p)return;let lista=leerFavoritos();const existe=lista.some(x=>Number(x.id)===Number(id));lista=existe?lista.filter(x=>Number(x.id)!==Number(id)):[{id:p.id,nombre:p.nombre,precio:precioFinal(p),imagen:imagenProducto(p),tienda:p.tienda||p.marca||'TiendaPro',estado_visual:p.estado_visual||'',guardado_en:Date.now()},...lista];localStorage.setItem(claveFavoritos(),JSON.stringify(lista));const btn=e.currentTarget;btn.classList.toggle('active',!existe);btn.setAttribute('aria-pressed',String(!existe));btn.title=existe?'Agregar a favoritos':'Quitar de favoritos';aviso(existe?'Producto eliminado de favoritos.':'Producto guardado en favoritos.')}
function restante(fecha){if(!fecha)return null;const ms=new Date(fecha).getTime()-Date.now();if(!Number.isFinite(ms))return null;if(ms<=0)return{expired:true,text:'Oferta finalizada'};let s=Math.floor(ms/1000),d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),sec=s%60;return{text:d>0?`Termina en ${d} d ${String(h).padStart(2,'0')} h ${String(m).padStart(2,'0')} min`:`Termina en ${String(h).padStart(2,'0')} h ${String(m).padStart(2,'0')} min ${String(sec).padStart(2,'0')} s`}}
function actualizarContadores(){document.querySelectorAll('[data-offer-end]').forEach(el=>{const r=restante(el.dataset.offerEnd);if(!r){el.textContent='⏱ Oferta por tiempo limitado';el.classList.add('no-date');return}el.textContent='⏱ '+r.text;el.classList.toggle('expired',!!r.expired)})}
function render(){
  const grid=$('#productosPublicos'),estado=$('#estadoPublico');
  if(!productos.length){grid.innerHTML='';estado.hidden=false;estado.textContent='En este momento no hay productos en oferta. Vuelve pronto para descubrir nuevos descuentos.';return}
  estado.hidden=true;
  grid.innerHTML=productos.map(p=>{
    const d=Number(p.descuento||0),base=Number(p.coincidencia_variante?.precio??p.precio??0),stock=Number(p.coincidencia_variante?.stock??p.stock_fisico_disponible??p.stock??0),img=imagenProducto(p),rating=Number(p.calificacion_promedio||0),reviews=Number(p.total_resenas||0),entrega=String(p.tiempo_entrega||'Según disponibilidad').trim(),favorito=esFavorito(p.id),cantidad=cantidadCarrito(p.id),agotado=stock<=0&&!p.permite_bajo_pedido;
    return `<article class="product-card product-card-clickable" role="link" tabindex="0" data-product-id="${p.id}"><div class="product-image">${img?`<img src="${img}" alt="${esc(p.nombre)}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span class="placeholder" style="display:none">📦</span>`:'<span class="placeholder">📦</span>'}<span class="product-discount-ribbon offer-ribbon">Oferta -${d}%</span><div class="product-actions"><button class="product-action-favorite ${favorito?'active':''}" type="button" title="${favorito?'Quitar de favoritos':'Agregar a favoritos'}" aria-label="${favorito?'Quitar de favoritos':'Agregar a favoritos'}" aria-pressed="${favorito}" data-card-favorite-id="${p.id}">❤</button></div></div><div class="product-body"><div class="product-brand">${esc(p.tienda||p.marca||'TiendaPro')}</div><h3 class="product-title">${esc(p.nombre)}</h3><div class="product-delivery-time"><span aria-hidden="true">🚚</span><span>Entrega: ${esc(entrega)}</span></div><div class="product-category">${esc(p.categoria||'')}</div><div class="product-rating"><span class="product-rating-stars">${stars(rating)}</span><span class="product-rating-text">${reviews?`${rating.toFixed(1)} (${reviews})`:'Sin reseñas'}</span></div><div class="badges"><span class="badge ${stock>0?'ok':'warn'}">${stock>0?'Disponible':'Agotado'}</span>${stock>0?`<span class="badge">Stock ${stock}</span>`:''}</div><div class="price-row"><span class="price">${money(precioFinal(p))}</span><span class="old-price">${money(base)}</span><button class="product-action-cart ${cantidad>0?'has-items':''}" type="button" data-card-cart-id="${p.id}" title="${agotado?'Producto agotado':'Agregar al carrito'}" ${agotado?'disabled':''}>🛒<span class="product-cart-quantity" ${cantidad>0?'':'hidden'}>${cantidad}</span></button></div><div class="offer-countdown" data-offer-end="${esc(p.fecha_fin_oferta||'')}">⏱ Calculando tiempo...</div></div></article>`
  }).join('');
  grid.querySelectorAll('[data-card-cart-id]').forEach(btn=>btn.addEventListener('click',e=>agregarDesdeTarjeta(e,btn.dataset.cardCartId)));
  grid.querySelectorAll('[data-card-favorite-id]').forEach(btn=>btn.addEventListener('click',e=>alternarFavorito(e,btn.dataset.cardFavoriteId)));
  grid.querySelectorAll('[data-product-id]').forEach(c=>{const go=()=>location.href=`producto.html?id=${c.dataset.productId}`;c.addEventListener('click',go);c.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();go()}})});
  actualizarContadores();clearInterval(timer);timer=setInterval(actualizarContadores,1000);
}
function params(){return new URLSearchParams({ofertas:'1',orden:$('#ordenPublico').value,page:String(pagina),limit:'20'})}
async function cargar(reset=false){if(reset)pagina=1;const e=$('#estadoPublico');e.hidden=true;try{const r=await fetch(`${API}/productos/publicos?${params()}`);if(!r.ok)throw new Error();meta=await r.json();productos=meta.productos||[];render();paginar();const n=Number(meta.total||productos.length);$('#resumenProductos').textContent=`${n} producto${n===1?'':'s'} con descuento`}catch{productos=[];$('#productosPublicos').innerHTML='';e.hidden=false;e.textContent='No se pudieron cargar las ofertas. Verifica que el servidor esté ejecutándose.';$('#resumenProductos').textContent='Ofertas no disponibles'}}
function paginar(){const box=$('#paginacionPublica'),total=Number(meta.totalPaginas||1);if(total<=1){box.innerHTML='';return}let h=`<button ${pagina<=1?'disabled':''} data-page="${pagina-1}">‹</button>`;for(let i=Math.max(1,pagina-2);i<=Math.min(total,pagina+2);i++)h+=`<button class="${i===pagina?'active':''}" data-page="${i}">${i}</button>`;h+=`<button ${pagina>=total?'disabled':''} data-page="${pagina+1}">›</button>`;box.innerHTML=h;box.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{const x=Number(b.dataset.page);if(x>=1&&x<=total){pagina=x;cargar();scrollTo({top:0,behavior:'smooth'})}})}
$('#ordenPublico').addEventListener('change',()=>cargar(true));cargar(true);
})();
