(()=>{
const API='http://localhost:3000/api',BASE=API.replace(/\/api$/,''),id=new URLSearchParams(location.search).get('id'),$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>'$'+Number(v||0).toFixed(2),price=p=>Number(p.precio||0)*(1-Number(p.descuento||0)/100),img=p=>{const v=String(p||'');return /^https?:\/\//i.test(v)?v:v.startsWith('/uploads/')?BASE+v:'';};
const socialIcons={"whatsapp": "<svg class=\"p-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 11.5A9 9 0 0 1 7.5 19L2 21l1.8-5A9 9 0 1 1 21 11.5Z\"/><path d=\"M8 7c-3 2 4 10 8 8l-2-3-2 1-2-2 1-2-3-2Z\"/></svg>", "correo_publico": "<svg class=\"p-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\"/><path d=\"m3 6 9 7 9-7\"/></svg>", "sitio_web": "<svg class=\"p-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"9\"/><ellipse cx=\"12\" cy=\"12\" rx=\"4\" ry=\"9\"/><path d=\"M3 12h18\"/></svg>", "instagram": "<svg class=\"p-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5\"/><circle cx=\"12\" cy=\"12\" r=\"4\"/><circle cx=\"17.5\" cy=\"6.5\" r=\".6\" fill=\"currentColor\"/></svg>", "facebook": "<svg class=\"p-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path fill=\"currentColor\" stroke=\"none\" d=\"M14 22v-9h3l.5-4H14V7c0-1.1.4-2 2-2h2V1.5C17 1.2 16 1 15 1c-3.5 0-5 2-5 5v3H7v4h3v9Z\"/></svg>"};
let data,category='',visible=20,tab='informacion',timer;
const iconPaths={pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',truck:'<path d="M2 5h12v12H2V5Zm12 4h5l3 5v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',shield:'<path d="m12 2 8 3v7c0 5-8 10-8 10S4 17 4 12V5l8-3Z"/><path d="m8 12 3 3 5-6"/>',support:'<path d="M3 14v-3a9 9 0 0 1 18 0v3M3 11h4v8H3v-8Zm14 0h4v8h-4v-8Z"/>',star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1 3-6Z"/>',cart:'<path d="M2 3h3l3 13h11l3-10H6"/><circle cx="9" cy="21" r="1"/><circle cx="18" cy="21" r="1"/>',chat:'<path d="M21 11a9 9 0 0 1-14 7l-5 3 1-6A9 9 0 1 1 21 11Z"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${iconPaths[name]||iconPaths.shield}</svg>`;
function read(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}}
function toast(text){$('#sellerToast').textContent=text;$('#sellerToast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#sellerToast').hidden=true,3000);}
function card(p){const favorite=read('tiendapro_productos_favoritos').some(x=>Number(x)===Number(p.id)),rating=Number(p.resenas.promedio),stock=Number(p.stock||0),url=img(p.imagen);return `<article class="seller-product"><a href="producto.html?id=${p.id}" class="seller-product-image">${url?`<img loading="lazy" src="${esc(url)}" alt="${esc(p.nombre)}">`:'<span>Sin imagen</span>'}</a>${Number(p.descuento)>0?'<span class="seller-offer">Oferta</span>':''}<button class="seller-favorite ${favorite?'selected':''}" data-favorite="${p.id}" aria-label="Guardar producto como favorito" aria-pressed="${favorite}">❤</button><div class="seller-product-body"><a href="producto.html?id=${p.id}">${esc(p.nombre)}</a><div class="seller-product-rating"><span>★</span> ${rating?rating.toFixed(1):'Sin reseñas'} ${p.resenas.total?`(${p.resenas.total})`:''}</div><div class="seller-product-price"><strong>${money(price(p))}</strong>${Number(p.descuento)>0?`<del>${money(p.precio)}</del>`:''}<button data-cart="${p.id}" aria-label="Agregar al carrito" ${stock<=0&&!p.permite_bajo_pedido?'disabled':''}>${icon('cart')}</button></div></div></article>`;}
function bindCards(host){host.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>{let list=read('tiendapro_productos_favoritos');const pid=Number(b.dataset.favorite),has=list.some(x=>Number(x)===pid);list=has?list.filter(x=>Number(x)!==pid):[...list,pid];localStorage.setItem('tiendapro_productos_favoritos',JSON.stringify(list));renderProducts();renderBest();toast(has?'Producto quitado de favoritos':'Favorito guardado en este navegador');});host.querySelectorAll('[data-cart]').forEach(b=>b.onclick=async()=>{
const p=data.productos.find(p=>Number(p.id)===Number(b.dataset.cart));if(!p)return;
b.disabled=true;try{
const response=await fetch(API+'/productos/publicos/'+p.id),detail=await response.json();if(!response.ok)throw Error(detail.mensaje||'No se pudo revisar el producto');const current=detail.producto;
if(current.presentaciones?.length){location.href='producto.html?id='+p.id;return;}
const stock=Number(current.stock||0);if(stock<=0&&!current.permite_bajo_pedido)throw Error('Este producto está agotado.');
const cart=read('tiendapro_carrito_publico'),item=cart.find(x=>Number(x.id)===Number(p.id)&&!x.variante_id&&!x.presentacion_id);if(item&&stock>0&&Number(item.cantidad)>=stock)throw Error('Ya tienes el stock disponible en el carrito.');
if(item)item.cantidad=Number(item.cantidad||0)+1;else cart.push({key:p.id+':0:0',id:p.id,variante_id:null,presentacion_id:null,nombre:current.nombre,precio:price(current),imagen:img(current.imagen),cantidad:1});
localStorage.setItem('tiendapro_carrito_publico',JSON.stringify(cart));const count=cart.reduce((n,x)=>n+Number(x.cantidad||0),0);for(const el of document.querySelectorAll('#sharedCartCount,#sharedCartCountCliente'))el.textContent=count;toast('Producto agregado al carrito.');
}catch(e){toast(e.message);}finally{b.disabled=false;}
});}
function renderBest(){const products=[...data.productos].filter(p=>Number(p.vendidos)>0).sort((a,b)=>b.vendidos-a.vendidos).slice(0,5);$('#bestGrid').innerHTML=products.map(card).join('')||'<p class="seller-empty">Esta tienda aún no registra productos vendidos en pedidos entregados.</p>';bindCards($('#bestGrid'));}
function renderProducts(){let products=[...data.productos];const search=$('#buscarTienda').value.trim().toLocaleLowerCase('es');if(category)products=products.filter(p=>String(p.categoria||'Otros')===category);if(search)products=products.filter(p=>[p.nombre,p.marca,p.categoria].some(v=>String(v||'').toLocaleLowerCase('es').includes(search)));const order=$('#ordenTienda').value;products.sort(order==='menor'?(a,b)=>price(a)-price(b):order==='mayor'?(a,b)=>price(b)-price(a):order==='nuevos'?(a,b)=>b.id-a.id:(a,b)=>b.vendidos-a.vendidos||b.id-a.id);$('#allGrid').innerHTML=products.slice(0,visible).map(card).join('')||'<p class="seller-empty">No hay productos para mostrar.</p>';$('#cargarProductos').hidden=products.length<=visible;bindCards($('#allGrid'));}
function setTab(name){tab=name;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name));});$('#bestSection').hidden=!['informacion','vendidos'].includes(name);$('#allSection').hidden=!['informacion','productos'].includes(name);$('#commentsSection').hidden=name!=='comentarios';$('#policiesSection').hidden=name!=='informacion';}
function contactUrl(key,value){if(key==='correo_publico')return 'mailto:'+value;if(key==='whatsapp')return /^https?:\/\//i.test(value)?value:'https://wa.me/'+value.replace(/\D/g,'');if((key==='instagram'||key==='facebook')&&!/^https?:\/\//i.test(value))return 'https://www.'+key+'.com/'+value.replace(/^@/,'');return /^https?:\/\//i.test(value)?value:'';}
function renderReviews(){const r=data.resumen;$('#sellerReviews').innerHTML=`<h2>${icon('star')} Reseñas de clientes</h2><strong class="seller-rating-total">${r.total?r.promedio.toFixed(1)+' de 5':'Sin reseñas'}</strong><p>${r.total} reseñas de productos</p><div class="seller-rating-bars">${[5,4,3,2,1].map(star=>{const n=r.total?Math.round(100*r.distribucion[star]/r.total):0;return `<div><span>${star} ★</span><progress value="${n}" max="100" aria-label="${star} estrellas: ${n}%"></progress><span>${n}%</span></div>`}).join('')}</div><button id="verResenas" class="seller-more">Ver todas las reseñas →</button>`;$('#verResenas').onclick=()=>setTab('comentarios');$('#commentsList').innerHTML=data.resenas.map(r=>`<article class="seller-comment"><strong>${esc(r.cliente?.split(' ')[0]||'Cliente')} · ${'★'.repeat(Number(r.calificacion))}</strong><small>Compra verificada · ${new Date(r.fecha_creacion).toLocaleDateString('es-SV')}</small><a href="producto.html?id=${r.producto_id}">${esc(r.producto)}</a><p>${esc(r.comentario)}</p></article>`).join('')||'<p>Todavía no hay comentarios publicados.</p>';$('#reviewsPagination').innerHTML=data.resenas_paginas>1?`<button data-review-page="${data.resenas_pagina-1}" ${data.resenas_pagina===1?'disabled':''}>Anterior</button><span>${data.resenas_pagina} / ${data.resenas_paginas}</span><button data-review-page="${data.resenas_pagina+1}" ${data.resenas_pagina>=data.resenas_paginas?'disabled':''}>Siguiente</button>`:'';$('#reviewsPagination').querySelectorAll('button').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await fetch(`${API}/productos/publicos/tiendas/${encodeURIComponent(id)}?resenas_pagina=${b.dataset.reviewPage}`);if(!r.ok)throw Error();data=await r.json();renderReviews();}catch{toast('No se pudieron cargar los comentarios');b.disabled=false;}});}
function render(){const t=data.tienda,c=t.perfil_publico||{},r=data.resumen,logo=img(t.logo_tienda),banner=img(t.banner_tienda);document.title=t.tienda+' | TiendaPro';$('#sellerHero').innerHTML=`<div class="seller-banner">${banner?`<img src="${esc(banner)}" alt="Banner de ${esc(t.tienda)}">`:''}</div><div class="seller-summary"><div class="seller-identity"><div class="seller-logo">${logo?`<img src="${esc(logo)}" alt="Foto de ${esc(t.tienda)}">`:esc(t.tienda.charAt(0).toUpperCase())}</div><div><h1>${esc(t.tienda)}</h1><p class="seller-level">${esc(t.nivel||'Vendedor TiendaPro')}</p><div class="seller-stats"><span>${icon('star')} <strong>${r.total?r.promedio.toFixed(1):'Sin reseñas'}</strong> (${r.total} reseñas)</span><span>${icon('cart')} <strong>${data.ventas.toLocaleString('es-SV')}</strong> unidades vendidas</span><span>${icon('shield')} <strong>${r.satisfaccion===null?'—':r.satisfaccion+'%'}</strong> reseñas positivas</span>${t.creado_en?`<span>En TiendaPro desde ${new Date(t.creado_en).getFullYear()}</span>`:''}</div></div></div><div class="seller-summary-bottom"><div><p>${esc(t.descripcion_publica||'El vendedor aún no ha agregado una descripción.')}</p><div class="seller-actions"><button id="seguirTienda">＋ Seguir tienda</button><button id="contactarTienda">${icon('chat')} Contactar</button></div></div><div class="seller-benefits"><span>${icon('shield')}<br>Políticas de<br>garantía</span><span>${icon('truck')}<br>Información<br>de envíos</span><span>${icon('support')}<br>Atención<br>al cliente</span></div></div></div>`;
const followed=read('tiendapro_tiendas_seguidas').some(x=>Number(x)===Number(t.id));$('#seguirTienda').textContent=followed?'✓ Siguiendo tienda':'＋ Seguir tienda';$('#seguirTienda').onclick=()=>{let list=read('tiendapro_tiendas_seguidas'),has=list.some(x=>Number(x)===Number(t.id));list=has?list.filter(x=>Number(x)!==Number(t.id)):[...list,t.id];localStorage.setItem('tiendapro_tiendas_seguidas',JSON.stringify(list));$('#seguirTienda').textContent=has?'＋ Seguir tienda':'✓ Siguiendo tienda';toast('Preferencia guardada en este navegador');};
const contactos=c.mostrar_contacto===false?[]:['whatsapp','correo_publico','instagram','facebook','sitio_web'].filter(k=>c[k]);$('#contactarTienda').disabled=!contactos.length;$('#contactarTienda').onclick=()=>$('#sellerContact').scrollIntoView({behavior:'smooth',block:'center'});
$('#sellerInfo').innerHTML=`<h2>Información de la tienda</h2><ul class="seller-info-list"><li>${icon('pin')} ${esc([c.ubicacion,c.pais].filter(Boolean).join(', ')||'Ubicación sin indicar')}</li><li>${icon('clock')} Tiempo de respuesta: ${esc(c.tiempo_respuesta||'Sin indicar')}</li>${c.direccion_publica?`<li>${icon('pin')} ${esc(c.direccion_publica)}</li>`:''}<li>${icon('clock')} <div>Horario:<br>Lunes a viernes: ${esc(window.TiendaProHorario.range(c.horario_semana))}<br>Sábado: ${esc(window.TiendaProHorario.range(c.horario_sabado))}<br>Domingo: ${esc(window.TiendaProHorario.range(c.horario_domingo))}</div></li></ul><hr><h2>Descripción de la tienda</h2><p>${esc(t.descripcion_publica||'Sin descripción.')}</p><div id="sellerContact"><h2>Contacto</h2>${contactos.map(key=>{const href=contactUrl(key,String(c[key]));return href?`<a class="seller-contact ${key}" href="${esc(href)}" target="_blank" rel="noopener noreferrer">${socialIcons[key]||icon('pin')} ${esc({whatsapp:'WhatsApp',correo_publico:'Correo electrónico',instagram:'Instagram',facebook:'Facebook',sitio_web:'Sitio web'}[key])} ↗</a>`:''}).join('')||'<p>El vendedor no ha publicado medios de contacto.</p>'}</div>`;
if(c.mapa_latitud!==undefined&&c.mapa_longitud!==undefined){const map=window.TiendaProMapa.crear(c.mapa_latitud,c.mapa_longitud,t.tienda);if(map){const title=document.createElement('h2');title.textContent='Ubicación en el mapa';$('#sellerInfo').append(title,map);}}
$('#policiesSection').innerHTML='<h2>Políticas de la tienda</h2>'+[['politica_envios','Envíos'],['politica_devoluciones','Devoluciones'],['garantia','Garantía de productos']].map(([key,name])=>`<details><summary>${name}</summary><p>${esc(c[key]||'El vendedor no ha agregado esta política.')}</p></details>`).join('');
const categories=[...new Set(data.productos.map(p=>String(p.categoria||'Otros')))];$('#sellerCategories').innerHTML=`<button class="active" data-category="">Todos (${data.productos.length})</button>`+categories.map(cat=>`<button data-category="${esc(cat)}">${esc(cat)} (${data.productos.filter(p=>String(p.categoria||'Otros')===cat).length})</button>`).join('');$('#sellerCategories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;visible=20;$('#sellerCategories').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderProducts();});renderBest();renderProducts();renderReviews();setTab(tab);
if(c.mostrar_productos===false){$('#allGrid').innerHTML='<p>El vendedor ha ocultado los productos de su perfil.</p>';$('#bestGrid').innerHTML='<p>El vendedor ha ocultado los productos de su perfil.</p>';}
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#verTodos').onclick=()=>{setTab('productos');$('#allSection').scrollIntoView({behavior:'smooth'});};$('#buscarTienda').oninput=()=>{visible=20;renderProducts();};$('#ordenTienda').onchange=()=>{visible=20;renderProducts();};$('#cargarProductos').onclick=()=>{visible+=20;renderProducts();};
(async()=>{try{if(!/^\d+$/.test(id||''))throw Error('Tienda no válida');const response=await fetch(API+'/productos/publicos/tiendas/'+encodeURIComponent(id));data=await response.json();if(!response.ok)throw Error(data.mensaje||'No se pudo cargar la tienda');render();$('#tiendaPublicaEstado').hidden=true;$('#perfilPublico').hidden=false;}catch(e){$('#tiendaPublicaEstado').textContent=e.message;}})();
})();
